### ISSUE TITLE
Gravitic Shield Issue

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#119]
old news, but I'll put it here anyway. 
Gravitic Shield Generator: boosting output should cost +Power per point. Current: +Basic Output per point.

Examples: 
Ikorta: Shield generator with Power usage of 2 and rating of 1. Each additional point should cost 2 (\current 1)
Brokados: power usage 5, rating 3: each additional point should cost 5 (current 3)

**Comment by AncientSion** [comment]
Lemme know if you need a hinter, like file or line. It might be confusing with the current file structure of FV. 
I have looked into it.

**Comment by tksolway** [comment]
I will, haven't had a chance to look into it just yet.  Very busy day just got more busy due to some layoffs.  I might not get to it for a couple days sorry.

**Comment by AncientSion** [comment]
Dont worry, this issue has been around since when Brakiri were introduced, that is 2, maybe 2.5 years ago and its a really minor deal.
Basicly, as far as im concerned, the constructor for the shield generator should be in basesystems.php.
this is the constructor function 
 
    function __construct($armour, $maxhealth, $powerReq, $output ){ 
      parent::__construct($armour, $maxhealth, $powerReq, $output ); 
      $this->boostEfficiency = $output; 
    }

basicly, the shield generators $output, which is supposed to be the amount of shields it can support, is as well set as the $boostEffiency. So a shieldGen always needs as much power to boost by one as it can support shields, which is just plain wrong, prolly an oversight.

All this needs is another variable in the constructor, like $boostEfficiency and then $this->boostEfficiency= $boostEfficiency.

As a last step, all "addPrimarySystem(new ShieldGenerator(xyz))" need to be adjusted by adding the actual boostEfficiency into it (in the ship files). 
Luckily, that would only be the Brokados, Torsha, Devaskar, Ikorta, Drikorta as class' as far as i remember.
That should solve this bug :)

**Comment by tksolway** [comment]
When you add power to a system does it just run the constructor again?

**Comment by tksolway** [comment]
I think this needs to be handled in the JS files under Power rather than in the constructor.  Looking at how the Scanner is handled.  I'm still trying to figure it all out though.

**Comment by tksolway** [comment]
Heh, nevermind, I just looked up the Rules.  

It is possible to activate more than the standard number
of shields at a significant power cost. For each additional
shield, the ship must apply power equal to the amount the
shield generator requires (as shown in the diamond power
icon next to the generator). For example, a generator with
a “4” in the diamond icon would require 4 extra power to
activate an extra shield, 8 power for two shields, etc.

So the generator does only require a single valule for boosted output, but it required the power requirement of the generator, not the output.  simple bug fix :-)  I'll upload the changed branch in a minute.  I also fixed a couple typos I found.
