### ISSUE TITLE
Organization of the Fleet Buy Window

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#148]
With more ships, and the addition of unofficial ships the rolls, it becomes necessary to "sort" the fleet buy window.  

At the very minimum we will need a "folder" underneath each faction for labeled unofficial. And ideally I would like to start sorting some of the ships in the classes.  I think simply separating out the fighters and stationary bases/osats would be a good start.  However, we could move farther by sorting all ships into classes (MCV, HCV, etc.).

I've taken a look at the functions that sort the ships in factions and then build the initially hidden lists.  I assume we would need to build sublists in each faction and then populate those with ships?  I'm not going to lie, the implementation here is beyond anything I've done before.  So if anyone could explain it, that would be great.

**Comment by AncientSion** [comment]
If one was to tackle the fleet buy window, the most useful approach would be to create a new, windows-explorer like structure, where instead of expanding a faction and listing all ships by class name, you would expand by faction and then would only see common vessels, which would be expandable as well to then show the variants of the expanded "common" baseships.

i.e. 

- EA
 - Apollo
 - Hyperion (pulse)
   - Hyperion (rail)
    - Hyperion (plasma)
 - Orestes (laser)
   - Orestes (plasma)
 - Warlock


I think this approach would make more sense then sorting by ship type.
I thought about it some time ago but discarded it.

Sorting by cap/hcv/mcv would have the advantage that this information is already embedded in the existing data. 
Sorting by variants like i suggested is not doable without altering existing shipfiles, because there is no defintion of what exactly a "base design" is, apart from variant data like common/uncommon/rare.


tell me the file and a line number and i can take a look at it. In general, Aatu does almost everything with a whole bunch of in-depth jQuery. If you dont know jQuery, you could do free tutorials at codeacademy for example, for the basics.

**Comment by tksolway** [comment]
I like this idea as well, a simple solution to the base identification is having a rarity level of "b".  Again, it would take some work to ensure that all ships have their rarities entered properly, but that's the type of work I can do eventually.  As a temporary measure we could simply have the rarity assigned as "b" in the to level constructor, then all ships would be a tree head until they are properly sorted.  

That being said.  I think that we would still need to separate out of the unofficial ships somehow.  We could do the (WOTCR) route and just make them a separate faction, but that would actually affect jammers.  

If we were to rebuild the ship buy list as you suggest would it be possible to add folders to it?

I don't know jQuery, I'd have to look into it before I take this on.  

I believe that the list is generated in Gamelobby.js Line55.  Although, I could be wrong.

**Comment by tksolway** [comment]
Didn't think about this part.  The ship will need to refer to its base class, not just have a rarity attached.  Easiest way would simply be to have another variable that is null in base classes but then is equal the phpclass of the base class in variants.

**Comment by Zero1627** [comment]
'base class' and 'common variant' are essentially equal. So 'base variant' can be simply assigned 'common' status - just need to keep all ships on one hull to point to the same variant as its base.

**Comment by tksolway** [comment]
Good Point, that would work too.

**Comment by Zero1627** [comment]
will do it :)

**Comment by Zero1627** [comment]
Reorganization is, I believe, done. Ships need to be overhauled to take advantage of new display options, but that may be done gradually (as it is with ISD). EA is overhauled as a model fleet.
