### ISSUE TITLE
New Naming Standard

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#178]
So I announced a new naming standard on FB.  It should solve any issues we have with scouts and jammers and custom ships.  I think it will also make things a bit neater as well.  Please build any new ships to that standard, we'll have to include a cleanup of the current custom ships in the next SCS fix as well.  

Let me know what you think.

**Comment by Zero1627** [comment]
as stated on FB :) - seems all right, but I'd still want custom designs to be clearly separated. A way o do this may be to start their names with 'custom' information (instead of ending with it). This way all custom units will appear in one block, and so will official designs - they will not mix. 
Like:
Official Variant A
Official Variant B
(c) Alexis
(c) Beatrice

For entire custom races (Ch'Lonas) I think information should be given in directory itself:
Ch'Lonas (custom)
 - Tra'Vora Light Cruiser (2245)
(...)

**Comment by tksolway** [comment]
It might be easier to change the sorting algorithm for that ship building page to stick anything with (Unofficial) at the end of the list.  That being said, I generally like the idea of all ship classes residing together even if (Unofficial) ones get interspersed.  It should still be obvious which are official and which are not.

**Comment by Zero1627** [comment]
> It should still be obvious which are official and which are not.

Yes, it should be clear whether they are mixed or separate (as long as there's _something_ setting them different, anywhere). But if one wants just official ships, unofficial ones mixed it may be irritating - they would be for me at least. For a player not knowing which ones are which, who actually checks them in FV - this would be even more troublesome I imagine.
So I definitely prefer them to be in a separate block, visible on a glance.


>It might be easier to change the sorting algorithm

Such change is possible - but I see no point in it: (c) or (unoff.) or _somehing_  on the beginning makes algorithm change not necessary AND make such ships visually stand off (much more than something at end of name) - which is a good thing in my opinion.

**Comment by Zero1627** [comment]
>I generally like the idea of all ship classes residing together even if (Unofficial) ones get interspersed

I do not :) - at least not to the point they get mixed.

**Comment by Zero1627** [comment]
I'll do it as part of another thread, closing this one.
