### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#182]
The numbers don't add up on pulse weapons, I've started looking for this in all my games and it seems pretty constant.  I assume it's just the display and that the appropriate amount of damage is actually being done.  

![capture](https://cloud.githubusercontent.com/assets/14058786/15218416/11a1b732-181d-11e6-915d-dc343fe2d513.PNG)

**Comment by AncientSion** [comment]
When ANY weapon kills a system and then does overkill damage, but the overkill damage is fully absorbed by armour, then the overkill damage will NOT be counted as damage / armor damage for the purpose of the damage log.
So in that case, a bunch of 10 damage pulses overkilled into structure, but didnt actually dmg structure. So this overkilled-but-absorbed damage is not counted by the game.
94 Damage listed with 110 being done, im positive you lost 16 damage due to the primary armor soaking it up entirely.

**Comment by tksolway** [comment]
I figured it was something like that, thanks for confirming.

**Comment by Zero1627** [comment]
delete thread then?
