### ISSUE TITLE
Fusion Agitator Issue

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#187]
Both of these fusion agitators were double boosted, and it has a normal damage range of 16-70

![capture](https://cloud.githubusercontent.com/assets/14058786/15264064/a3e6663c-192c-11e6-99c1-e4535ffbb870.PNG)

There wasn't enough damage for any of these to overkill.  so we shouldn't have lost any to that.  I'll have to check how this weapon is implemented, especially with the boost, perhaps there is a bug there.

**Comment by AncientSion** [comment]
Its not only about overkill damage. If a system, regardless of overkill, soaks up a full volley via armour, it will also not be listed. Since Agitators do these small rakes, its possible that versus a high-armoured target, a bunch of damage will appear lost (didnt think about that in the other thread, the "soaking" problem shows up regardless of overkill or not).
However, the effective armour for a Agitator to be fully absorbed should be 7, which is unseen unless its Centauri armour. Also, as soon as a second rake hits the same system, the damage and armour will be counted.
Another explanation would be broken hitchart, voiding damage.

**Comment by tksolway** [comment]
Ya, I was thinking the hit chart as well, it was targeting a Bin'Tak, which doesn't have A7 on the front or side weapons.

**Comment by tksolway** [comment]
There is definitely an issue with the damage dealt, not just to display.

The minimum damage for a molecular disruptor is 32, Someone it did less than 20.

There doesn't seem to be any unaccounted for damage as there was exactly 42 damage done to that side, no extra, and the weapons did 42 damage.  The rakes for that volley are 10s so it shouldn't have wasted it all on armour and not reported it.  

![image](https://cloud.githubusercontent.com/assets/14058786/15271099/55f5de7e-19f6-11e6-9538-a752b0d4edfd.png)

**Comment by tksolway** [comment]
This ship got hit with two molecular disruptors for a total of 29 damage (including armour)  No other damage to the ship yet.  There is definitely an issue somewhere.  I'm going to have to do some tests to track it down.  

![capture](https://cloud.githubusercontent.com/assets/14058786/15271153/dabbaee8-19f8-11e6-8e71-c3cf3235aa61.PNG)

**Comment by tksolway** [comment]
Well, I can't find any reason why it would have done such a low amount of damage.  As far as I can tell everything looks good, I've parsed through the entire fire chain and can't find anything.  

Tests I've run on my own system seem to give the right amount of damage too.

That being said, there was obviously an issue in that game.

**Comment by tksolway** [comment]
I may have found the issue.  The new code since we implemented the different location hit chart now checks against different_location rather than location.  However, if a roll went to primary different_location was never changed.  So the system was looking for scanners and other primary systems in the wrong location.  I'll need to do some testing to see if this fixes the issue.

**Comment by AncientSion** [comment]
Considering the level of complexity, you always introduce at least 3 bugs when you add a new feature. Of a universal law :P

**Comment by tksolway** [comment]
Found a second bug as well.  The if statement that checks for primary had another set of hitchart checks after it.  They should have been in that if statement (so the second set only checks if we move to primary).  However, that second set was outside the if statement, so it would execute every time.  So we would have had issues where the second roll got primary but it wasn't passed to primary, causing more lost damage.  I will end up posting the branch pull so you both can see the code changes.

**Comment by tksolway** [comment]
I've also moved the location different check into an else off of the primary check.  I don't believe a ship exists that looks to shift a primary hit out of the primary so this should be fine and limit it's execution a bit.

**Comment by Zero1627** [comment]
thumbs up, Tom :)

**Comment by tksolway** [comment]
Not sure if I've completely fixed this issue yet.  I got a firing phase with this again, It was targeting a Narn Dread though.  I noticed that you had done an update to the Narn hit charts, were there issues there?

![capture](https://cloud.githubusercontent.com/assets/14058786/15516097/7656ac1a-21ae-11e6-9c89-4e8720f667d6.PNG)

**Comment by Zero1627** [comment]
Sho'Kos had TAs on hit chart (and LPCs as actual systems), so I corrected it.

But I'm doing Showdowns-10 Narns (unofficial) currently, and am doing minor corrections if I spot something off on official sheets. Also, many Narn ships in FV have just variant name without type description, I correct that too when spotted (example: "Ka'Toc" -> "Ka'Toc Battle Destroyer").

As for Your issue, I see it's with Molecular Disruptors again. Perhaps it's something specific to this weapon?... (haven't checked if it uses any special targeting routines, but it's possible due to special effect).

**Comment by Zero1627** [comment]
as I'm gutting firing procedures pretty completely, I'm sure old bugs will be gone. 
Of course, new ones will take their place...
