### ISSUE TITLE
WotCR enhancements

### ISSUE THREAD

**Issue by Zero1627** [Aatu/FieryVoid#718]
WotCR describes a few unit enhancements that can be easily implemented in FV< giving options (not just for the Centauri ;) .

Those are:
HOT refit for fighters (WotCR Centauri only)
Unprofessional ship (probably would have to be simplified, but Ini hit would be easy)
Vulnerable to criticals
Sluggish (again modified for simplicity - +0.1 turn cost and delay?...)

**Comment by melkorium** [comment]
Hi Marcin, I was looking at 'Sluggish' as one the Descari ship, Scorota,  has this 'enhancement'.  It's a 2D6 initiative penalty in tabletop so I was either going to check if '-roll(d6,2)' could be used as its $this->iniativebonusvalue (prolly not), or have a fixed -7 value as the average of that dice roll.  So maybe the enhancement would work best as an initiative penalty rather than a change to turn cost/delay?

The same ship is also vulnerable to critical but I see there's already a value for that - $this->critRollMod - which I was going to set to 1.

The does beg the question over whether new enhancements would impact on the Scorata i.e. if it starts with these enhancements by default what happens if you select them again.  I guess, it's maybe not a major issue to double ini penalty and critical vulnerability in terms of game mechanics, but god help the crew of that ship!

**Comment by Zero1627** [comment]
A modification can be easily blocked for a given ship, so unit that has a mod included in design (and shouldn't be able to take it again) is not a problem.

**Comment by Zero1627** [comment]
Sluggish and Vulnerable to Criticals added - both scalable, both with very low estimated cost (thought about as scenario modifier rather than something to actually consider at fleet selection... usually :) ).

H.O.T. Refit: I can't find, will add when I find it in a sourcebook.

Other don't seem all that suitable for FieryVoid

**Comment by Zero1627** [comment]
Found Improved Self Repair: +1 repair output, max +50%, price: new value *100 - thic should certainly be coded in :)

**Comment by Zero1627** [comment]
I'll close it.
